language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

before_script: pip install docker-compose

script:
  - echo No tests yet
  - docker-compose build
  - docker-compose up -d
  - docker-compose run --rm api sh -c "pytest"