version: "3.9"

services: 
  api:
    image: abhijithganesh/sahaay
    container_name: Jumping_Jose
    # Docker container Name will be Dancing Rose
    
    #Environment File
    # env_file:
    #    - Core/.env
    
    #commands which will be executed
    command: python3 manage.py migrate
    command: python3 manage.py collectstatic
    command: uvicorn Core.asgi:fastapi --proxy-headers --host 0.0.0.0 --port 8080

    #ports that would be exposed
    ports:
       - 8080:8080
    environment:
        - DB_URL=postgres://db/sahaayDB
         
    # Links the directory ./app to the docker volume
    # app 
    volumes:
        - ./design:/design
        - ./Core:/Core
  
  db:
    image: postgres
    container_name: database_postgres

#     env_file:
#         - db.env
    ports:
        - 5432:5432
    volumes:
        - taskdb:/data/db
volumes:
    taskdb:
