version: "3.8"

services: 
  fast-api:
    build: 
      #Defines which directory this app builds.
      #Currently configured to base/root directory
      context: . 
    container_name: fast-api
    restart: always
    ports:
      #Maps our local port 80 
      #to docker image port 80 
      - "80:80" 