version: "3.8"

services: 
  
  api:
    container_name: fastapi
    # Associates the directory called app with this
    # Docker container
    build: ./app
    # The port 80 is connected to the docker image 
    # port 80
    ports: 
        - 3000:3000
    
    # Sets environment variables
    environment:
        - DB_URL=mongodb://db/sahaayDB
    
    # Links the directory ./app to the docker volume
    # app 
    volumes:
        - ./app:/app
  
  db:
    image: mongo
    container_name: database_mongo
    ports:
        - 27018:27018
    volumes:
        - taskdb:/data/db
volumes:
    taskdb: