version: "3.8"

services: 
  
  api:
    container_name: fastapi
    # Associates the directory called app with this
    # Docker container
    build: .
    # The port 80 is connected to the docker image 
    # port 80
    ports: 
        - 3000:3000
    
    # Sets environment variables
    environment:
        - DB_URL=postgres://db/sahaayDB
        - SECRET_KEY=4ab5be85c8c56eecdd547f7831979be83de58a6768d10a314f54cda4e4d67ffe
    
    # Links the directory ./app to the docker volume
    # app 
    volumes:
        - ./Core:/Core
  
  db:
    image: postgres
    container_name: database_postgres
    ports:
        - 27018:27018
    volumes:
        - taskdb:/data/db
volumes:
    taskdb: